# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20160228_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '\u0406\u0441\u043f\u0438\u0442', 'verbose_name_plural': '\u0406\u0441\u043f\u0438\u0442\u0438'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examiner',
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner',
            field=models.ManyToManyField(max_length=255, null=True, to='students.Student', verbose_name='\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447'),
        ),
    ]
