# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20160228_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='examiner',
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447'),
        ),
    ]
