# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_exam_rating_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='rating_exam',
        ),
    ]
